name: pagefault-pokerogue-prod

services:
  pokerogue:
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    container_name: pokerogue
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - pokerogue-storage:/app/dist
    networks:
      - internal
      - pagefault-pokerogue-net

volumes:
  pokerogue-storage:

networks:
  internal:
    internal: true
  pagefault-pokerogue-net:
    external: true
